services:
  database:
    image: 'postgres:17.4'
    restart: always
    ports:
      - '5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=task2'
  s3mock:
    image: 'adobe/s3mock:4.1.1'
    environment:
      - 'initialBuckets=UserImages'
      - 'retainFilesOnExit=true'
    ports:
      - '9090:9090'
    volumes:
      - ./locals3root:/containers3root
  mqueue:
    image: 'softwaremill/elasticmq-native:1.6.12'
    ports:
      - '9325:9325'
      - '9324:9324'
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    environment:
      - ELASTICMQ_CONFIG=/opt/elasticmq.conf
volumes:
  db:
    driver: local