include classpath("application.conf")

queues {
  SendMail {
    defaultVisibilityTimeout = 15 seconds
    delay = 10 seconds
    receiveMessageWait = 5 seconds
    fifo = false
    contentBasedDeduplication = false
    name="SendMail"
  }
}