upstream apps {
    server app1:8080 weight=2 fail_timeout=15s;
    server app2:8080 weight=8 fail_timeout=15s;
}

server {
    listen 9090;
    location / {
        proxy_redirect off;
        proxy_pass http://apps;
        proxy_set_header   X-Forwarded-Host $server_name;
    }
}